services:
  expressapp:
    image: waltteriw/express-app:latest
    container_name: expressapp
    ports:
      - "3000:8080"
    restart: always

  watchtower:
    image: containrrr/watchtower
    environment:
      -  WATCHTOWER_POLL_INTERVAL=60
    command: expressapp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower
